name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Compilation
      run: gcc -o result function.h function.c projectmain.c
    #- name: Execution
    #  run: ./result
